Vberenz/pamy2
intelligent-soft-robots/pam_interface pull request #6
Opened 2022-02-25 10:47 UTC by vincentberenz

[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

### pamy2
Added new code for the support of the new pamy2 robot, reusing abstract classes already used for pamy1.
These interfaces had to be refactored (minor changes), and the structure of the include folder had to be updated.

### mpi_cpp_format
I made the error to apply in the middle of my work the mpi_cpp_format, forgetting it had not been applied on the package yet. That made the diff with master almost unusable for review. Apologies for this.
To fix this, I updated the commits so that the bulk of the code to review will be in one commit (first commit) and the rest (reformatting and minor refactoring of existing code) would be in the second commit.
**please review only the code of the first commit ** (added new code for the support of the new pam robot pamy2).

## How I Tested

- there is a new demo (pamy2_udp_communication.cpp)
- the full software stack (i.e. up to learning table tennis from scratch) was run using the new robot

## Do not merge before

[//]: # "Link other open pull request here that need to be merged first."
[//]: # "Remove this section if it does not apply."

- [ ] link to dependent pull request

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

2022-02-25 10:49 UTC, vincentberenz commented
@luator @alexanderdittrich  comment just to emphasize: please review only the first commit ! (see Description)

2022-02-25 14:31 UTC, luator requested changes
Some files seem not to be formatted correctly (formatting check is failing)

2022-02-25 14:31 UTC, luator commented on src/udp_communication.cpp
> +    static const double to_radian = -0.0174533;
Writing `M_PI/180` instead of the resulting number would be a bit clearer.

2022-02-25 14:31 UTC, luator commented on src/udp_communication.cpp
> +    static const double to_radian = -0.0174533;
Also, using `constexpr` instead of `const` may result in better code optimisation (not sure if it really makes a difference, though).

2022-02-28 11:10 UTC, simonguist commented on src/pamy2_interface.cpp
> +            std::to_string(dof) + ": dof should be in range [1,3]");
range [0,3]

2022-02-28 11:42 UTC, simonguist commented on src/udp_communication.cpp
> +static TO cast_pressure(FROM value, FROM fmin, FROM fmax, TO tmax, TO tmin)
`TO tmax, TO tmin` should be `TO tmin, TO tmax`

2022-02-28 12:00 UTC, simonguist approved these changes

2022-02-28 15:39 UTC, vincentberenz commented
I made all the changes

2022-02-28 15:40 UTC, merged